(function(){
const STORAGE='samuel_comissoes_pro';
const NOME_USUARIO='controle_vendas_nome_usuario';
const OCULTAR='controle_vendas_ocultar_receber';
const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const vendas=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch(e){return[]}};
const dataLocal=t=>{const p=String(t||'').slice(0,10).split('-').map(Number);return p.length===3?new Date(p[0],p[1]-1,p[2]):null};
const atual=()=>{const n=new Date();return vendas().filter(v=>{const d=dataLocal(v.data);return d&&d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()})};
const tipoNormal=t=>String(t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const nomeVendedor=()=>localStorage.getItem(NOME_USUARIO)?.trim()||'Vendedor não informado';
function resumoTipo(lista,tipo){const f=lista.filter(v=>tipoNormal(v.tipo||v.tipoVenda)===tipo);return{qtd:f.length,total:f.reduce((s,v)=>s+Number(v.valor||0),0),lista:f}}
function imprimirTipo(tipo,titulo){const lista=atual().filter(v=>tipoNormal(v.tipo||v.tipoVenda)===tipo);if(!lista.length){alert('Nenhuma venda de '+titulo+' neste mês.');return}const total=lista.reduce((s,v)=>s+Number(v.valor||0),0);const linhas=lista.map(v=>`<tr><td>${dataLocal(v.data)?.toLocaleDateString('pt-BR')||''}</td><td>${v.cliente||''}</td><td>${v.produto||v.modelo||''}</td><td>${moeda(v.valor)}</td></tr>`).join('');const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${titulo}</title><style>body{font-family:Arial;padding:28px;color:#111}h1{color:#003b8e;margin:0}p{margin:6px 0}.nome{font-weight:bold;margin-top:8px}table{width:100%;border-collapse:collapse;margin-top:20px}th{background:#003b8e;color:#fff}th,td{border:1px solid #ccc;padding:8px;text-align:left}.total{text-align:right;font-size:18px;font-weight:bold;margin-top:18px}</style></head><body><h1>CONTROLE DE VENDAS PRO</h1><p>Relatório individual — ${titulo}</p><p class="nome">Vendedor: ${nomeVendedor()}</p><table><thead><tr><th>Data</th><th>Cliente</th><th>Produto/Modelo</th><th>Valor</th></tr></thead><tbody>${linhas}</tbody></table><div class="total">Total: ${moeda(total)}</div><script>setTimeout(()=>window.print(),400)<\/script></body></html>`);w.document.close()}
function render(){const d=document.getElementById('dashboard');if(!d)return;const lista=atual();const total=lista.reduce((s,v)=>s+Number(v.valor||0),0);const comissao=lista.reduce((s,v)=>s+Number(v.comissao||0),0);const c=resumoTipo(lista,'consorcio'),f=resumoTipo(lista,'financiamento'),a=resumoTipo(lista,'a vista');const oculto=localStorage.getItem(OCULTAR)!=='false';const nome=localStorage.getItem(NOME_USUARIO)||'';
d.innerHTML=`<div class="painel-cabecalho"><h1 class="painel-titulo">CONTROLE DE VENDAS</h1><span class="painel-dono">Samuel Mendes Sathler</span></div><div class="perfil-v2"><div class="avatar-perfil">👤</div><div class="perfil-textos"><button id="editarNomeV2" class="nome-editavel"><h1>${nome||'Seu nome'}</h1><span>✏️</span></button><p>${nome?'Toque para alterar':'Toque para definir'}</p></div></div><section class="resumo-v2"><h2>📊 RESUMO DO MÊS</h2><div class="resumo-grid"><div class="resumo-item resumo-vendas"><span class="resumo-icone azul">🛒</span><strong>${lista.length}</strong><small>VENDAS</small></div><div class="resumo-item resumo-faturamento"><span class="resumo-icone verde">$</span><strong>${moeda(total)}</strong><small>FATURAMENTO</small></div><div class="resumo-item resumo-comissao"><span class="resumo-icone laranja">👁</span><strong id="valorReceberV2">${oculto?'Oculto':moeda(comissao)}</strong><small>COMISSÃO A RECEBER</small><button id="toggleReceberV2" class="olho-btn">👁 ${oculto?'MOSTRAR':'OCULTAR'}</button></div></div></section><section class="tipos-v2"><div class="tipos-cabecalho"><h2>🏷️ VENDAS POR TIPO DE NEGOCIAÇÃO</h2><button onclick="abrirTela('relatorios')">Ver detalhes ›</button></div><div class="tipos-grid">${card('consorcio','🤝','CONSÓRCIO',c)}${card('financiamento','💳','FINANCIAMENTO',f)}${card('avista','💵','À VISTA',a)}</div></section><section class="acoes-v2"><h2>⚡ AÇÕES RÁPIDAS</h2><div class="acoes-grid"><button class="acao-v2" onclick="abrirTela('relatorios')"><span>📄</span>Relatório mensal<br><small>Imprimir / PDF</small></button><button class="acao-v2" onclick="abrirTela('relatorios')"><span>🗓️</span>Relatório anual<br><small>Imprimir / PDF</small></button><button class="acao-v2" onclick="abrirTela('backup')"><span>☁️</span>Backup<br><small>Exportar</small></button><button class="acao-v2" onclick="abrirTela('backup')"><span>♻️</span>Restaurar<br><small>Importar</small></button></div></section><button class="nova-venda-v2" onclick="abrirTela('novaVenda')">＋ NOVA VENDA</button>`;
d.querySelector('#editarNomeV2').onclick=()=>{const n=prompt('Digite o nome que deseja mostrar no aplicativo:',localStorage.getItem(NOME_USUARIO)||'');if(n!==null){localStorage.setItem(NOME_USUARIO,n.trim());render()}};d.querySelector('#toggleReceberV2').onclick=()=>{localStorage.setItem(OCULTAR,String(!oculto));render()};d.querySelectorAll('[data-imprimir]').forEach(b=>b.onclick=()=>imprimirTipo(b.dataset.imprimir,b.dataset.titulo));}
function card(classe,icone,titulo,r){const tipo=classe==='avista'?'a vista':classe;return `<article class="tipo-card ${classe}"><div class="tipo-conteudo"><span class="tipo-icone">${icone}</span><h3>${titulo}</h3><div class="qtd">${r.qtd}</div><small>vendas</small><div class="tipo-linha"></div><div class="tipo-valor">${moeda(r.total)}</div><button class="tipo-imprimir" data-imprimir="${tipo}" data-titulo="${titulo}">🖨️ IMPRIMIR</button></div></article>`}
window.atualizarDashboardV2=render;document.addEventListener('DOMContentLoaded',render);const original=window.atualizarDashboard;window.atualizarDashboard=function(){if(original)original();render()};})();