const CACHE_NAME = 'samuel-comissoes-pro-v121';
const APP_SHELL = [
  './','./index.html','./style.css?v=4','./dashboard-v2.css?v=7','./home-four-columns-fix.css?v=2','./visual-match.css?v=3','./bottom-layout-fix.css?v=1','./brand-cleanup.css?v=1','./responsive-layout.css?v=3','./tipo-numeros-mobile.js?v=3','./analise-vendas.css?v=1','./mobile-alignment-fix.css?v=1','./analise-vendas.js?v=5','./pwa-enhancements.js?v=17','./ai-performance-accelerator.js?v=2','./user-management-unified.js?v=7','./user-management-reference.css?v=2','./user-management-modern-v2.js?v=2026.07.21.6','./firebase-integration.js?v=8','./script.js?v=4','./dashboard-v2.js?v=10','./bottom-nav-auto-hide.js?v=5','./ia-guardia-24h.js?v=1','./ia-guardia-autocorrecao.js?v=1','./ia-guardia-24h.css?v=2','./guardian-admin-only.js?v=3','./guardian-firestore-bridge.js?v=1','./guardian-gear-integration.js?v=3','./guardian-audit-upgrade.js?v=2','./guardian-offline-filter.js?v=1','./safari-indexeddb-transaction-fix.js?v=1','./guardian-deep-audit.js?v=4','./guardian-autofix.js?v=3','./guardian-retention.js?v=1','./guardian-occurrences-safe.js?v=2','./guardian-actions-organizer.js?v=1','./guardian-repository-knowledge.js?v=1','./guardian-actions-functional.js?v=1','./guardian-app-manifest.json','./manifest.json?v=15','./apple-touch-icon.png?v=15','./icon-192.png?v=15'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>Promise.allSettled(APP_SHELL.map(url=>cache.add(url)))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_NAME&&!key.startsWith('scp-ai-warm-')).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE_TESTED_VERSION'||event.data?.type==='SKIP_WAITING')self.skipWaiting()});
function redePrimeiro(request){return fetch(request,{cache:'no-store'}).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy))}return response}).catch(()=>caches.match(request))}
function cachePrimeiro(request){return caches.match(request).then(cached=>{const atualizar=fetch(request,{cache:'no-store'}).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy))}return response}).catch(()=>cached);return cached||atualizar})}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.pathname.endsWith('/version.json')||url.pathname.endsWith('/guardian-app-manifest.json')){event.respondWith(fetch(event.request,{cache:'no-store'}));return}if(event.request.mode==='navigate'){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put('./index.html',copy))}return response}).catch(()=>caches.match('./index.html').then(cached=>cached||caches.match('./'))));return}if(url.origin===self.location.origin){const arquivoDinamico=/\.(js|json|html|css)$/.test(url.pathname);event.respondWith(arquivoDinamico?redePrimeiro(event.request):cachePrimeiro(event.request));return}event.respondWith(fetch(event.request).catch(()=>caches.match(event.request))) });